Name:           perl-AutoXS-Header
Version:        1.01
Release:        1%{?dist}
Epoch:          1
Summary:        Container for the AutoXS header files
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AutoXS-Header/
Source0:        http://www.cpan.org/modules/by-module/AutoXS/AutoXS-Header-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is a simple container for the newest version of the AutoXS
header file AutoXS.h.

%prep
%setup -q -n AutoXS-Header-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Sep 03 2009 Casper Pedersen <cpedersen@c-note.dk> 1.01-1
- Specfile autogenerated by cpanspec 1.77.
