Name:           perl-FCGI
Version:        0.67
Release:        1%{?dist}
Summary:        FCGI Perl module
License:        Distributable, see LICENSE.TERMS
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/FCGI/
Source0:        http://www.cpan.org/modules/by-module/FCGI/FCGI-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Copyright (c) 1996 Open Market, Inc. See the file "LICENSE.TERMS" for
information on usage and redistribution of this file, and for a DISCLAIMER
OF ALL WARRANTIES.

%prep
%setup -q -n FCGI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog configure.readme FCGI.XL LICENSE.TERMS README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/FCGI*
%{_mandir}/man3/*

%changelog
* Wed Jan 14 2009 cpedersen 0.67-1
- Specfile autogenerated by cpanspec 1.77.
